version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    container_name: curita-bot
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_DB_HOST=mysql
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_PORT=3306
      - NODE_ENV=production
    volumes:
      - bot-sessions:/app/bot_sessions
    # Utilizamos init: true para mejor manejo de procesos
    init: true
    networks:
      - curita-network
    ports:
      - "3000:3000"  # Permite acceso desde cualquier IP
    security_opt:
      - no-new-privileges:true

  mysql:
    image: mysql:8.0
    container_name: curita-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bd/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./bd/script.sql:/docker-entrypoint-initdb.d/02-script.sql:ro
    ports:
      - "127.0.0.1:3307:3306"
    security_opt:
      - no-new-privileges:true
    networks:
      - curita-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=200 --wait-timeout=28800
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=root", "--password=${MYSQL_DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local
  bot-sessions:
    driver: local

networks:
  curita-network:
    driver: bridge
